import pandas as pd

cols = ["enc", "dec"]

# filename = "strings_key_val_dec.csv"
filename = "6_enc_map.csv"

df = pd.read_csv(filename, index_col="enc", names=cols).to_dict()

with open("codeit - Copy_.au3", "r") as f:
  dec_content = f.read()
f.close()

mapped = {'arehdidxrgk($os[$flmhuqjxlm])': ' struct;uint bfSize;uint bfReserved;uint bfOffBits;uint biSize;int biWidth;int biHeight;ushort biPlanes;ushort biBitCount;uint biCompression;uint biSizeImage;int biXPelsPerMeter;int biYPelsPerMeter;uint biClrUsed;uint biClrImportant;endstruct;',
'arehdidxrgk($os[$flxnxnkthd])': ' bfSize',
'arehdidxrgk($os[$flmhuqjxlm])': ' struct;uint bfSize;uint bfReserved;uint bfOffBits;uint biSize;int biWidth;int biHeight;ushort biPlanes;ushort biBitCount;uint biCompression;uint biSizeImage;int biXPelsPerMeter;int biYPelsPerMeter;uint biClrUsed;uint biClrImportant;endstruct;',
'arehdidxrgk($os[$flmhuqjxlm])': ' struct;uint bfSize;uint bfReserved;uint bfOffBits;uint biSize;int biWidth;int biHeight;ushort biPlanes;ushort biBitCount;uint biCompression;uint biSizeImage;int biXPelsPerMeter;int biYPelsPerMeter;uint biClrUsed;uint biClrImportant;endstruct;',
'arehdidxrgk($os[$flldooqtbw])': ' bfReserved',
'arehdidxrgk($os[$flsfwhkphp])': ' bfOffBits',
'arehdidxrgk($os[$flmvwpfapg])': ' biSize',
'arehdidxrgk($os[$fliwyjfdak])': ' biWidth',
'arehdidxrgk($os[$fltsjlagjo])': ' biHeight',
'arehdidxrgk($os[$flvaxmaxna])': ' biPlanes',
'arehdidxrgk($os[$flsfkralzh])': ' biBitCount',
'arehdidxrgk($os[$flsoprhueg])': ' biCompression',
'arehdidxrgk($os[$flbzbcwqxo])': ' biSizeImage',
'arehdidxrgk($os[$flmmexivfs])': ' biXPelsPerMeter',
'arehdidxrgk($os[$flzzzdhszn])': ' biYPelsPerMeter',
'arehdidxrgk($os[$flfsohvcfj])': ' biClrUsed',
'arehdidxrgk($os[$flfstfcrlf])': ' biClrImportant',
'arehdidxrgk($os[$flhxyjqrtq])': ' struct;',
'arehdidxrgk($os[$fluyicwqbf])': ' byte[',
'arehdidxrgk($os[$flsxztehyj])': ' biWidth',
'arehdidxrgk($os[$flhdlfyqrt])': ' ];',
'arehdidxrgk($os[$flqfroneda])': ' biHeight',
'arehdidxrgk($os[$flbrxfhgjg])': ' endstruct',
'arehdidxrgk($os[$flxupdtbky])': ' ',
'arehdidxrgk($os[$flramjdyfu])': ' .bmp',
'arehdidxrgk($os[$flukndiwex])': ' \\',
'arehdidxrgk($os[$flsgbzulnf])': ' .dll',
'arehdidxrgk($os[$flhanaxdhn])': ' \\',
'arehdidxrgk($os[$flaexdqsrh])': ' struct;dword;char[1024];endstruct',
'arehdidxrgk($os[$flsnpewutk])': ' kernel32.dll',
'arehdidxrgk($os[$flamfdduxi])': ' int',
'arehdidxrgk($os[$flcwfyxdtf])': ' GetComputerNameA',
'arehdidxrgk($os[$flafbzxahu])': ' ptr',
'arehdidxrgk($os[$flskiskqti])': ' ptr',
'arehdidxrgk($os[$flfbevuldl])': ' CodeIt Plus!',
'arehdidxrgk($os[$floyeoxjvb])': ' struct;byte[',
'arehdidxrgk($os[$fluodjmwgw])': ' ];endstruct',
'arehdidxrgk($os[$fltibtjhtt])': ' struct;byte[54];byte[',
'arehdidxrgk($os[$fljevdjxae])': ' ];endstruct',
'arehdidxrgk($os[$flauqlvkxg])': ' ',
'arehdidxrgk($os[$flxzrpavsw])': ' struct;byte[',
'arehdidxrgk($os[$flmdifziop])': ' ];endstruct',
'arehdidxrgk($os[$fldfpzzafd])': ' struct;ptr;ptr;dword;byte[32];endstruct',
'arehdidxrgk($os[$fljdtvsdso])': ' advapi32.dll',
'arehdidxrgk($os[$flexjevbco])': ' int',
'arehdidxrgk($os[$flxquvzrly])': ' CryptAcquireContextA',
'arehdidxrgk($os[$flshmemjjj])': ' ptr',
'arehdidxrgk($os[$flhqjglfws])': ' ptr',
'arehdidxrgk($os[$flwvzhffsc])': ' ptr',
'arehdidxrgk($os[$flfrtkctqe])': ' dword',
'arehdidxrgk($os[$fljhsdaeav])': ' dword',
'arehdidxrgk($os[$flvoretncd])': ' advapi32.dll',
'arehdidxrgk($os[$flyxdicudb])': ' int',
'arehdidxrgk($os[$flcrgsivod])': ' CryptCreateHash',
'arehdidxrgk($os[$flanaocmrr])': ' ptr',
'arehdidxrgk($os[$flvzomlpcy])': ' dword',
'arehdidxrgk($os[$flnponcvdb])': ' dword',
'arehdidxrgk($os[$flkgskcvuw])': ' dword',
'arehdidxrgk($os[$flfmpbdwej])': ' ptr',
'arehdidxrgk($os[$flfwmyxvvj])': ' advapi32.dll',
'arehdidxrgk($os[$fljcjbfhkv])': ' int',
'arehdidxrgk($os[$flggfvewxl])': ' CryptHashData',
'arehdidxrgk($os[$flnxzdbehd])': ' ptr',
'arehdidxrgk($os[$fluktgcieq])': ' struct*',
'arehdidxrgk($os[$fllueubehx])': ' dword',
'arehdidxrgk($os[$fllrdexkdn])': ' dword',
'arehdidxrgk($os[$flgrkcxavd])': ' advapi32.dll',
'arehdidxrgk($os[$flhqanofav])': ' int',
'arehdidxrgk($os[$flzjxicupp])': ' CryptGetHashParam',
'arehdidxrgk($os[$flxdfspfko])': ' ptr',
'arehdidxrgk($os[$flsermhiop])': ' dword',
'arehdidxrgk($os[$flcnxxwsyv])': ' ptr',
'arehdidxrgk($os[$fldbgphumx])': ' ptr',
'arehdidxrgk($os[$flxubnstgs])': ' dword',
'arehdidxrgk($os[$fletewazkh])': ' 0x',
'arehdidxrgk($os[$flabbihpaw])': ' 8020',
'arehdidxrgk($os[$flbymtwvbx])': ' 10',
'arehdidxrgk($os[$flgcijtdlm])': ' 66000',
'arehdidxrgk($os[$fljjiooifn])': ' 2000',
'arehdidxrgk($os[$flxfeftbwv])': ' 0',
'arehdidxrgk($os[$flticitoyz])': ' 0x',
'arehdidxrgk($os[$flmstpwbrq])': ' CD4B3',
'arehdidxrgk($os[$flecuynwdb])': ' 2C650',
'arehdidxrgk($os[$fljicvvbxq])': ' CF21B',
'arehdidxrgk($os[$fltonztzlf])': ' DA184',
'arehdidxrgk($os[$flsbpkavsy])': ' D8913',
'arehdidxrgk($os[$flxpwifgkd])': ' E6F92',
'arehdidxrgk($os[$flwxylvbjs])': ' 0A37A',
'arehdidxrgk($os[$flgckmzayx])': ' 4F396',
'arehdidxrgk($os[$fltwuwurss])': ' 3736C',
'arehdidxrgk($os[$fljlijhegu])': ' 042C4',
'arehdidxrgk($os[$flwswtvquf])': ' 59EA0',
'arehdidxrgk($os[$flyatafxxs])': ' 7B79E',
'arehdidxrgk($os[$flswkvicqg])': ' A443F',
'arehdidxrgk($os[$flevoknzhs])': ' FD189',
'arehdidxrgk($os[$flezsvlbbu])': ' 8BAE4',
'arehdidxrgk($os[$flvtqedrnc])': ' 9B115',
'arehdidxrgk($os[$flusnuqyrh])': ' F6CB1',
'arehdidxrgk($os[$flryydwmeb])': ' E2A7C',
'arehdidxrgk($os[$flpxkdtiub])': ' 1AB3C',
'arehdidxrgk($os[$flmfelfgbm])': ' 4C256',
'arehdidxrgk($os[$flaqvpxefd])': ' 12A51',
'arehdidxrgk($os[$flctnooltz])': ' 9035F',
'arehdidxrgk($os[$flgdvxhtzc])': ' 18FB3',
'arehdidxrgk($os[$flwehnunfj])': ' B1752',
'arehdidxrgk($os[$fllonnyibc])': ' 8B3AE',
'arehdidxrgk($os[$fllzjoogng])': ' CAF3D',
'arehdidxrgk($os[$floduobscm])': ' 4.80E+11',
'arehdidxrgk($os[$flgtvyiwta])': ' 8BF8A',
'arehdidxrgk($os[$flevlqhfzo])': ' 635DA',
'arehdidxrgk($os[$floodysbvz])': ' F974E',
'arehdidxrgk($os[$flzluahbyv])': ' 135',
'arehdidxrgk($os[$flvnfpqxze])': ' 35D23',
'arehdidxrgk($os[$flaiqgjntx])': ' 1E4B7',
'arehdidxrgk($os[$flcwlffkhm])': ' 5B2C3',
'arehdidxrgk($os[$flqcqufhqv])': ' 8B804',
'arehdidxrgk($os[$flrbuzyvzf])': ' C7AE4',
'arehdidxrgk($os[$flwvicvsms])': ' D266A',
'arehdidxrgk($os[$flcpbndhbq])': ' 37B36',
'arehdidxrgk($os[$fliecjfrpe])': ' F2C55',
'arehdidxrgk($os[$flghxsbhmp])': ' 5BF3A',
'arehdidxrgk($os[$floaidmlpx])': ' 9EA6A',
'arehdidxrgk($os[$fllvmncnny])': ' 58BC8',
'arehdidxrgk($os[$flsfutymly])': ' F906C',
'arehdidxrgk($os[$fluhbelzbi])': ' C665E',
'arehdidxrgk($os[$flmnjwehod])': ' AE2CE',
'arehdidxrgk($os[$flimuxorrr])': ' 60F2C',
'arehdidxrgk($os[$flwlkknrpp])': ' DE38F',
'arehdidxrgk($os[$flhblipjbm])': ' D3026',
'arehdidxrgk($os[$flubwwkeml])': ' 9CC4C',
'arehdidxrgk($os[$fljufrnthn])': ' E5BB0',
'arehdidxrgk($os[$flktybyfdh])': ' 90472',
'arehdidxrgk($os[$flcrizoigp])': ' FF9BD',
'arehdidxrgk($os[$fldrutgtai])': ' 26F91',
'arehdidxrgk($os[$fljwnwaben])': ' 19B8C',
'arehdidxrgk($os[$flxdasfsup])': ' 484FE',
'arehdidxrgk($os[$flvtsklnds])': ' 69EB9',
'arehdidxrgk($os[$flgmzabuwz])': ' 34F43',
'arehdidxrgk($os[$flwrppuxsb])': ' FEEDE',
'arehdidxrgk($os[$flmnmtpcbt])': ' DCEBA',
'arehdidxrgk($os[$fltgxuvxht])': ' 79146',
'arehdidxrgk($os[$fltkwhzfio])': ' 0819F',
'arehdidxrgk($os[$flxzavwmtk])': ' B21F1',
'arehdidxrgk($os[$flmiginejb])': ' 0F832',
'arehdidxrgk($os[$fltcctsiso])': ' B2A5D',
'arehdidxrgk($os[$flvolubnxk])': ' 4D772',
'arehdidxrgk($os[$flxvccpzhb])': ' DB12C',
'arehdidxrgk($os[$flbyzxyfqo])': ' 3BED9',
'arehdidxrgk($os[$flophsmbek])': ' 47F6F',
'arehdidxrgk($os[$fldpastqqh])': ' 706AE',
'arehdidxrgk($os[$flvmfptzcs])': ' 4411A',
'arehdidxrgk($os[$flxireqgpl])': ' 52',
'arehdidxrgk($os[$flhfdxuudy])': ' struct;ptr;ptr;dword;byte[8192];byte[',
'arehdidxrgk($os[$flfmfyahhr])': ' ];dword;endstruct',
'arehdidxrgk($os[$fllsbiddpb])': ' advapi32.dll',
'arehdidxrgk($os[$fluopltsma])': ' int',
'arehdidxrgk($os[$flbnlstaug])': ' CryptAcquireContextA',
'arehdidxrgk($os[$flywhxdmqv])': ' ptr',
'arehdidxrgk($os[$flgfnzsvnj])': ' ptr',
'arehdidxrgk($os[$flbucrjuwo])': ' ptr',
'arehdidxrgk($os[$flyafxnzcb])': ' dword',
'arehdidxrgk($os[$flxpzbcwes])': ' dword',
'arehdidxrgk($os[$flveiodzpl])': ' advapi32.dll',
'arehdidxrgk($os[$flroncrwtg])': ' int',
'arehdidxrgk($os[$flmymaytor])': ' CryptImportKey',
'arehdidxrgk($os[$flbkxrnxpv])': ' ptr',
'arehdidxrgk($os[$flmgldspdj])': ' ptr',
'arehdidxrgk($os[$fltgdgujkn])': ' dword',
'arehdidxrgk($os[$fltzqiggdk])': ' dword',
'arehdidxrgk($os[$flnyytfkei])': ' dword',
'arehdidxrgk($os[$flznxmaqlq])': ' ptr',
'arehdidxrgk($os[$flrmmepznf])': ' advapi32.dll',
'arehdidxrgk($os[$flkctwjxsv])': ' int',
'arehdidxrgk($os[$flxznyhvmb])': ' CryptDecrypt',
'arehdidxrgk($os[$flzkhknuxv])': ' ptr',
'arehdidxrgk($os[$flfhwpdvdv])': ' dword',
'arehdidxrgk($os[$flhaajvxmt])': ' dword',
'arehdidxrgk($os[$flhukovwky])': ' dword',
'arehdidxrgk($os[$flguylaqhb])': ' ptr',
'arehdidxrgk($os[$fltzvugnmn])': ' ptr',
'arehdidxrgk($os[$flfnyyixlr])': ' FLARE',
'arehdidxrgk($os[$flgsadhexo])': ' ERALF',
'arehdidxrgk($os[$fljmhypfzy])': ' advapi32.dll',
'arehdidxrgk($os[$flcscartxg])': ' int',
'arehdidxrgk($os[$flatlaxfun])': ' CryptDestroyKey',
'arehdidxrgk($os[$flkyehpfcl])': ' ptr',
'arehdidxrgk($os[$flsbvdgrpi])': ' advapi32.dll',
'arehdidxrgk($os[$flhmejjpgg])': ' int',
'arehdidxrgk($os[$flvtvyiyzu])': ' CryptReleaseContext',
'arehdidxrgk($os[$flvvrrdevf])': ' ptr',
'arehdidxrgk($os[$flsvnuqocx])': ' dword',
'arehdidxrgk($os[$flnpzlyjmk])': ' advapi32.dll',
'arehdidxrgk($os[$flvcsigzxl])': ' int',
'arehdidxrgk($os[$flpuowucoh])': ' CryptDestroyHash',
'arehdidxrgk($os[$fliccbnvun])': ' ptr',
'arehdidxrgk($os[$floaipmnkp])': ' advapi32.dll',
'arehdidxrgk($os[$flmlupdwyw])': ' int',
'arehdidxrgk($os[$flrynetwbg])': ' CryptReleaseContext',
'arehdidxrgk($os[$flpytxgnae])': ' ptr',
'arehdidxrgk($os[$flyxgoankm])': ' dword',
'arehdidxrgk($os[$flgiybxvqu])': ' struct;ptr;ptr;dword;byte[16];endstruct',
'arehdidxrgk($os[$flidkfvoer])': ' advapi32.dll',
'arehdidxrgk($os[$fljhxpdlgl])': ' int',
'arehdidxrgk($os[$flfqexpzzc])': ' CryptAcquireContextA',
'arehdidxrgk($os[$flkfnstomi])': ' ptr',
'arehdidxrgk($os[$flioplujrx])': ' ptr',
'arehdidxrgk($os[$flqonphkjt])': ' ptr',
'arehdidxrgk($os[$flwcdnzybe])': ' dword',
'arehdidxrgk($os[$flofosbflo])': ' dword',
'arehdidxrgk($os[$fldcdylywl])': ' advapi32.dll',
'arehdidxrgk($os[$fllvmmtgod])': ' int',
'arehdidxrgk($os[$flhvcbzfrn])': ' CryptCreateHash',
'arehdidxrgk($os[$fltrngarjy])': ' ptr',
'arehdidxrgk($os[$flkxleyzxr])': ' dword',
'arehdidxrgk($os[$flbjfbsnip])': ' dword',
'arehdidxrgk($os[$flswnjceva])': ' dword',
'arehdidxrgk($os[$fljhoxspca])': ' ptr',
'arehdidxrgk($os[$fldensetkm])': ' advapi32.dll',
'arehdidxrgk($os[$flixvxwcri])': ' int',
'arehdidxrgk($os[$flmjfdjlzq])': ' CryptHashData',
'arehdidxrgk($os[$flsmzhobco])': ' ptr',
'arehdidxrgk($os[$flgckwhruk])': ' struct*',
'arehdidxrgk($os[$flvqlgyufz])': ' dword',
'arehdidxrgk($os[$flshmkxxuh])': ' dword',
'arehdidxrgk($os[$flcuwkmzyt])': ' advapi32.dll',
'arehdidxrgk($os[$flycibmgpd])': ' int',
'arehdidxrgk($os[$flitcabdow])': ' CryptGetHashParam',
'arehdidxrgk($os[$fliclftine])': ' ptr',
'arehdidxrgk($os[$flinelzznd])': ' dword',
'arehdidxrgk($os[$fleqczuvlg])': ' ptr',
'arehdidxrgk($os[$flokxreddk])': ' ptr',
'arehdidxrgk($os[$flywdvownk])': ' dword',
'arehdidxrgk($os[$flyabzrrmv])': ' advapi32.dll',
'arehdidxrgk($os[$flpuwwmbao])': ' int',
'arehdidxrgk($os[$flouvibzyw])': ' CryptDestroyHash',
'arehdidxrgk($os[$flmrudhnhp])': ' ptr',
'arehdidxrgk($os[$flhhpbrjke])': ' advapi32.dll',
'arehdidxrgk($os[$flrkparhzh])': ' int',
'arehdidxrgk($os[$flnycpueln])': ' CryptReleaseContext',
'arehdidxrgk($os[$flnegilmwq])': ' ptr',
'arehdidxrgk($os[$flyqwvfhlw])': ' dword',
'arehdidxrgk($os[$flqjtxmafd])': ' struct;dword;dword;dword;dword;dword;byte[128];endstruct',
'arehdidxrgk($os[$flzlvskjaw])': ' kernel32.dll',
'arehdidxrgk($os[$flrxmffbjl])': ' int',
'arehdidxrgk($os[$flvlzpmufo])': ' GetVersionExA',
'arehdidxrgk($os[$fldcvsitmj])': ' struct*',
'arehdidxrgk($os[$flktwrjohv])': ' Enter text to encode',
'arehdidxrgk($os[$flpxfiylod])': ' Can haz code?',
'arehdidxrgk($os[$flchkrzxfi])': ' ',
'arehdidxrgk($os[$fljrlgnyxn])': ' Help',
'arehdidxrgk($os[$flgoleifxh])': ' About CodeIt Plus!',
'arehdidxrgk($os[$flewckibqf])': ' struct;dword;dword;byte[3918];endstruct',
'arehdidxrgk($os[$flfbhdcwrz])': ' int:cdecl',
'arehdidxrgk($os[$flvjhzdfox])': ' justGenerateQRSymbol',
'arehdidxrgk($os[$flzaqhexft])': ' struct*',
'arehdidxrgk($os[$flcgkjfdha])': ' str',
'arehdidxrgk($os[$flsvrwfrhg])': ' int:cdecl',
'arehdidxrgk($os[$floehubdbq])': ' justConvertQRSymbolToBitmapPixels',
'arehdidxrgk($os[$flqaltypjs])': ' struct*',
'arehdidxrgk($os[$flyxawteum])': ' struct*',
'arehdidxrgk($os[$flkkjswqsg])': ' .bmp',
'arehdidxrgk($os[$flkaiidxzu])': 'This program generates QR codes using QR Code Generator (https: //www.nayuki.io/page/qr-code-generator-library)',
'arehdidxrgk($os[$flghbwhiij])': 'QR Code Generator is available on GitHub (https: //github.com/nayuki/QR-Code-generator)',
'arehdidxrgk($os[$flawuytxzy])': 'Copyright Ã‚Â© 2020 Project Nayuki. (MIT License)',
'arehdidxrgk($os[$flkuoykdct])': ' https://www.nayuki.io/page/qr-code-generator-library',
'arehdidxrgk($os[$flqjzijekx])': ' Permission is hereby granted',
'arehdidxrgk($os[$fldbkumrch])': ' 1. The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.',
'arehdidxrgk($os[$flvmxyzxjh])': ' 2. The Software is provided as is',
'arehdidxrgk($os[$flscevepor])': ' About CodeIt Plus!',
'arehdidxrgk($os[$flocqaiwzd])': ' struct;ushort;endstruct',
'arehdidxrgk($os[$flviysztbd])': ' biHeight',
'arehdidxrgk($os[$flfegerisy])': ' biHeight',
'arehdidxrgk($os[$flejpkmhdl])': ' struct;byte;byte;byte;endstruct',
'arehdidxrgk($os[$flemdcrqdd])': ' biWidth',
'arehdidxrgk($os[$flbafslfjs])': ' biWidth',
'arehdidxrgk($os[$flkhegsvel])': ' kernel32.dll',
'arehdidxrgk($os[$flxsdmvblr])': ' ptr',
'arehdidxrgk($os[$flikwkuqfw])': ' CreateFile',
'arehdidxrgk($os[$flhwrpeqlu])': ' str',
'arehdidxrgk($os[$flgeusyouv])': ' \\',
'arehdidxrgk($os[$fluscndcwl])': ' uint',
'arehdidxrgk($os[$flheifsdlr])': ' uint',
'arehdidxrgk($os[$flmkwzhgsx])': ' ptr',
'arehdidxrgk($os[$flkvvasynk])': ' uint',
'arehdidxrgk($os[$fllnvdsuzt])': ' uint',
'arehdidxrgk($os[$flqplzawir])': ' ptr',
'arehdidxrgk($os[$flqwweubdm])': ' kernel32.dll',
'arehdidxrgk($os[$flfxfgyxls])': ' ptr',
'arehdidxrgk($os[$fltwctunjp])': ' CreateFile',
'arehdidxrgk($os[$flojqsrrsp])': ' str',
'arehdidxrgk($os[$fljfqernut])': ' \\',
'arehdidxrgk($os[$flnzfzydoi])': ' uint',
'arehdidxrgk($os[$flompxsyzt])': ' uint',
'arehdidxrgk($os[$fleujcyfda])': ' ptr',
'arehdidxrgk($os[$flsunmubjt])': ' uint',
'arehdidxrgk($os[$flwfciovpd])': ' uint',
'arehdidxrgk($os[$flqxfkfbod])': ' ptr',
'arehdidxrgk($os[$fllkghuyoo])': ' kernel32.dll',
'arehdidxrgk($os[$flvoitvvcq])': ' uint',
'arehdidxrgk($os[$fltwxzcojl])': ' SetFilePointer',
'arehdidxrgk($os[$flabfakvap])': ' ptr',
'arehdidxrgk($os[$fldwmpgtsj])': ' long',
'arehdidxrgk($os[$flncsalwdm])': ' ptr',
'arehdidxrgk($os[$flxjexjhwm])': ' uint',
'arehdidxrgk($os[$flmmqocqpd])': ' uint',
'arehdidxrgk($os[$flcuyaggud])': ' kernel32.dll',
'arehdidxrgk($os[$flxkqpkzxq])': ' ptr',
'arehdidxrgk($os[$fllftzdhoa])': ' WriteFile',
'arehdidxrgk($os[$fliqyvcbyg])': ' ptr',
'arehdidxrgk($os[$fleuhchvkd])': ' ptr',
'arehdidxrgk($os[$fleyxmofxu])': ' uint',
'arehdidxrgk($os[$florzkpciq])': ' ptr',
'arehdidxrgk($os[$flhiqhcyio])': ' ptr',
'arehdidxrgk($os[$flmmqjhziv])': ' struct;dword;endstruct',
'arehdidxrgk($os[$flpdpbbqig])': ' kernel32.dll',
'arehdidxrgk($os[$flyugczhjh])': ' int',
'arehdidxrgk($os[$fliiemmoao])': ' ReadFile',
'arehdidxrgk($os[$flqbxxvjkp])': ' ptr',
'arehdidxrgk($os[$fllcwtuuxw])': ' struct*',
'arehdidxrgk($os[$flgcavcjkb])': ' dword',
'arehdidxrgk($os[$flizrncrjw])': ' struct*',
'arehdidxrgk($os[$flhbzvwdbm])': ' ptr',
'arehdidxrgk($os[$flbfviwghv])': ' kernel32.dll',
'arehdidxrgk($os[$flocbjosfl])': ' int',
'arehdidxrgk($os[$flijvrfukw])': ' CloseHandle',
'arehdidxrgk($os[$floufwdich])': ' ptr',
'arehdidxrgk($os[$flfawmkpyi])': ' kernel32.dll',
'arehdidxrgk($os[$flxsckorht])': ' int',
'arehdidxrgk($os[$flvegsawer])': ' DeleteFileA',
'arehdidxrgk($os[$flsvrbynni])': ' str',
'arehdidxrgk($os[$fltfnazynw])': ' struct;dword;endstruct',
'arehdidxrgk($os[$fltxcjfdtj])': ' kernel32.dll',
'arehdidxrgk($os[$flkgpmtrva])': ' dword',
'arehdidxrgk($os[$flgdedqzlq])': ' GetFileSize',
'arehdidxrgk($os[$flgsdeiksw])': ' ptr',
'arehdidxrgk($os[$flzgopkmys])': ' struct*',
'$flavekolca': "0",
'$flerqqjbmh': "1",
'$flowfrckmw': "0",
'$flmxugfnde': "0",
'$flvjxcqxyn': "2",
'$flddxnmrkh': "0",
'$flroseeflv': "1",
'$flpgrglpzm': "0",
'$flvzrkqwyg': "0",
'$flyvormnqr': "0",
'$flvthbrbxy': "1",
'$flxttxkikw': "0",
'$flgjmycrvw': "1",
'$flceujxgse': "0",
'$flhptoijin': "0",
'$flrzplgfoe': "0",
'$fliboupial': "0",
'$flidavtpzc': "1",
'$floeysmnkq': "1",
'$flaibuhicd': "0",
'$flekmapulu': "1",
'$flwecmddtc': "1",
'$flwjxfofkr': "0",
'$flhaombual': "0",
'$fldtvrladh': "1",
'$flpqigitfk': "1",
'$flbxttsong': "1",
'$fljlrqnhfc': "0",
'$flemdcrqdd': "6",
'$flmmamrwab': "3",
'$fldwuczenf': "1",
'$flrdaskyvd': "0",
'$flbafslfjs': "6",
'$flndzdxavp': "4",
'$flfgifsier': "1",
'$flfbqjbpgo': "1",
'$flsgvsfczm': "0",
'$flmzrdgblc': "0",
'$flcpxdpykx': "0",
'$flbddrzavr': "3",
'$flkpxipgal': "0",
'$flsxhsgaxu': "0",
'$flqfpqbvok': "0",
'$flrubfcaxm': "0",
'$flqcktzayy': "2",
'$fliwgresso': "0",
'$flywpbzmry': "0",
'$flqgmnikmi': "1",
'$flgmsyadmq': "2",
'$flocbwfdku': "1",
'$flgxbowjra': "2",
'$flmjqnaznu': "1",
'$flsgwhtzrv': "0",
'$flfvhrtddd': "0",
'$flrrpwpzrd': "3",
'$flrtxuubna': "1",
'$fljgtgzrsy': "1",
'$flsgrrbigg': "1",
'$fljkeopgvh': "1",
'$flsvfpdmay': "0",
'$flqwzpygde': "0",
'$flvjqtfsiz': "1",
'$flypdtddxz': "0",
'$flcxaaeniy': "1",
'$flxaushzso': "1",
'$flxxqlgcjv': "1",
'$flavacyqku': "0",
'$flviysztbd': "7",
'$flpdfbgohx': "0",
'$flfegerisy': "7",
'$flilknhwyk': "0",
'$floqyccbvg': "2",
'$flxigqoizb': "4",
'$flzwiyyjrb': "3",
'$flyxhsymcx': "0",
'$fltjkuqxwv': "0",
'$flalocoqpw': "0",
'$flklivkouj': "4",
'$fladcakznh': "2",
'$flbkjlbayh': "1",
'$flbxsazyed': "0",
'$flnbejxpiv': "1",
'$flmdzxmojv': "1",
'$flwdjhxtqt': "0",
'$flrqjwnkkm': "0",
'$flodkkwfsg': "2",
'$fleblutcjv': "6",
'$flusbtjhcm': "3",
'$flwwnbwdib': "1",
'$flhhamntzx': "0",
'$flallgugxb': "1",
'$flevbybfkl': "5",
'$flnmjxdkfm': "1",
'$flfkewoyem': "1",
'$fljmvkkukj': "1",
'$flulkqsfda': "0",
'$flbguybfjg': "3",
'$flvkhmevkl': "2",
'$flskoeixpo': "1",
'$fltygfaazw': "0",
'$fljsmlmnmb': "2",
'$flispmmify': "1",
'$fllcqiliyn': "0",
'$flckpfjmvi': "1",
'$flrslvnjmf': "3",
'$flnhhtfknm': "1",
'$flayrxawki': "0",
'$fldqffsiwv': "0",
'$flvfwrjmjd': "0",
'$flcvmqvlnh': "0",
'$flxxxstnev': "1",
'$flkhshkrug': "0",
'$flpomtleuc': "0",
'$flnzchdmsu': "2",
'$fljzhxwibz': "0",
'$flluwmjhex': "0",
'$flxifitlbz': "2",
'$flfxawzktb': "0",
'$flncksfusq': "0",
'$flszxbcaxw': "0",
'$flewlxbtze': "2",
'$flffkmnrin': "5",
'$flnxtetuvo': "6",
'$flvuvsuzbc': "0",
'$flzpwbdcwm': "0",
'$flfvgbqfsf': "2",
'$flqzhvgeiv': "0",
'$flkbpmewrr': "0",
'$flwjugkiiw': "2",
'$floicbrqfw': "0",
'$flcxrpcjhw': "1",
'$flmayhqwzl': "0",
'$fljtcwuidx': "4",
'$flgwubucwo': "3",
'$fllawknmko': "0",
'$flhuzjztma': "0",
'$flmeobqopq': "4",
'$fliycunpdr': "1",
'$flveglzons': "3",
'$flhsghsqkv': "1",
'$fltpqpqkpf': "1",
'$flqajqcgnb': "1",
'$flanjwgybt': "6",
'$fldzqrblug': "4",
'$flhdphdqob': "2",
'$flqopleteo': "4",
'$flmytlhxpo': "2",
'$flpevdrdlo': "0",
'$flptdindai': "0",
'$flgujvukws': "2",
'$flkawuusha': "0",
'$fljuolpkfq': "0",
'$flcnpjsxcg': "0",
'$flmhzummpo': "2",
'$flhrjkqvru': "2",
'$flobwiuvkw': "4",
'$flmvbxjfah': "3",
'$flqocsrbgg': "0",
'$flpocagrli': "0",
'$flwfneljwg': "0",
'$flevpvmavp': "4",
'$flfsjhegvq': "3",
'$flonfgetwp': "4",
'$flcxgmxxsz': "5",
'$flicpdewwo': "6",
'$flfaijogtb': "1",
'$flfajfokzy': "0",
'$flqykiuxho': "0",
'$flpcrftwvr': "0",
'$flvjdlwvhm': "0",
'$flqhepdeks': "1",
'$flrujstiki': "1",
'$flaefecieh': "1",
'$flaieigmma': "1",
'$flkvntcqfv': "6",
'$flmkmllsnu': "0",
'$flefscawij': "1",
'$flxeqkukpp': "2",
'$flsnjmvbtp': "1",
'$flfwydelan': "1",
'$flzoycekpn': "1",
'$flxxgkpivv': "1",
'$fltzjpmvxn': "1",
'$flftjybgvr': "7",
'$flztyfgltv': "1",
'$flflavkzaq': "1",
'$flmjfbnyec': "1",
'$flbigthxyk': "3",
'$fljijxqyzy': "1",
'$flgdnnqsti': "0",
'$flmbjrthgv': "0",
'$flyrtvauea': "0",
'$fldcgtnakv': "0",
'$flpifpmbzi': "1",
'$flchqqrkle': "0",
'$floezygqxe': "0",
'$flnyfquhrm': "0",
'$flhsoyzund': "0",
'$flcpgmnctu': "1",
'$flpkesjrhx': "0",
'$flsxztehyj': "6",
'$flnmnjaxtr': "3",
'$flgtnljovc': "0",
'$flqfroneda': "7",
'$flqzeldyni': "0",
'$flxzyfahhe': "1",
'$flrfdvckrf': "1",
'$flrdwakhla': "1",
'$fllazedtzj': "1",
'$fldbjqqaiy': "2",
'$flqhsoflsj': "1",
'$flopdvhjle': "0",
'$flpvxadmhh': "0",
'$fldcyeghlf': "2",
'$flpxlalosg': "1",
'$fldhthsnwj': "1",
'$flwtsvpqcx': "1",
'$flrrbxoggl': "1",
'$fltgqykodm': "1",
'$fltmxodmfl': "1",
'$flvujariho': "1",
'$flldooqtbw': "3",
'$flehogcpwq': "0",
'$flmbbmuicf': "0",
'$flsfwhkphp': "4",
'$flkkmdmfvj': "0",
'$flmvwpfapg': "5",
'$flfwgvtxrp': "0",
'$fliwyjfdak': "6",
'$fltypfarsj': "0",
'$fltsjlagjo': "7",
'$flwgmwwers': "0",
'$flvaxmaxna': "8",
'$flrjmgooql': "1",
'$fluoqiynkc': "0",
'$flsfkralzh': "9",
'$flgavmtume': "0",
'$flyaxyilnq': "0",
'$flhrjrmiis': "0",
'$flzwriuqzw': "0",
'$flvrhzzkvb': "0",
'$flydcwqgix': "0",
'$flymqghasv': "0",
'$flswvvhbrz': "0",
'$flyrzxtsgb': "0",
'$flafmmiiwn': "0",
'$flgcavcjkb': "36",
'$flizrncrjw': "39",
'$flhbzvwdbm': "28",
'$flbfviwghv': "25",
'$flocbjosfl': "26",
'$flijvrfukw': "156",
'$floufwdich': "28",
'$flfawmkpyi': "25",
'$flxsckorht': "26",
'$flvegsawer': "157",
'$flsvrbynni': "138",
'$fltfnazynw': "154",
'$fltxcjfdtj': "25",
'$flkgpmtrva': "36",
'$flgdedqzlq': "158",
'$flgsdeiksw': "28",
'$flzgopkmys': "39",
'$flmtlcylqk': "2",
'$flegviikkn': "0",
'$flmhuqjxlm': "1",
'$flmssjmyyw': "0",
'$flxnxnkthd': "2",
'$flhzxpihkn': "3",
'$flwioqnuav': "4",
'$flmivdqgri': "0",
'$flwfciovpd': "150",
'$flbrberyha': "128",
'$flqxfkfbod': "28",
'$fllkghuyoo': "25",
'$flvoitvvcq': "150",
'$fltwxzcojl': "151",
'$flabfakvap': "28",
'$fldwmpgtsj': "152",
'$flncsalwdm': "28",
'$flxjexjhwm': "150",
'$flmmqocqpd': "150",
'$flcuyaggud': "25",
'$flxkqpkzxq': "28",
'$fllftzdhoa': "153",
'$fliqyvcbyg': "28",
'$fleuhchvkd': "28",
'$fleyxmofxu': "150",
'$florzkpciq': "28",
'$flhiqhcyio': "28",
'$flmmqjhziv': "154",
'$flpdpbbqig': "25",
'$flyugczhjh': "26",
'$fliiemmoao': "155",
'$flqbxxvjkp': "28",
'$fllcwtuuxw': "39",
'$flyhhitbme': "19778",
'$flejpkmhdl': "148",
'$flkhegsvel': "25",
'$flxsdmvblr': "28",
'$flikwkuqfw': "149",
'$flhwrpeqlu': "138",
'$flgeusyouv': "22",
'$fluscndcwl': "150",
'$flozjuvcpw': "2147483648",
'$flheifsdlr': "150",
'$flmkwzhgsx': "28",
'$flkvvasynk': "150",
'$fllnvdsuzt': "150",
'$flgzyedeli': "128",
'$flqplzawir': "28",
'$flqwweubdm': "25",
'$flfxfgyxls': "28",
'$fltwctunjp': "149",
'$flojqsrrsp': "138",
'$fljfqernut': "22",
'$flnzfzydoi': "150",
'$fleiynadiw': "1073741824",
'$flompxsyzt': "150",
'$fleujcyfda': "28",
'$flsunmubjt': "150",
'$flnepnlrbe': "26",
'$flewckibqf': "135",
'$flfbhdcwrz': "136",
'$flvjhzdfox': "137",
'$flzaqhexft': "39",
'$flcgkjfdha': "138",
'$flpzzbelga': "1024",
'$flsvrwfrhg': "136",
'$floehubdbq': "139",
'$flqaltypjs': "39",
'$flyxawteum': "39",
'$flzhydqkfa': "25",
'$flxjnumurx': "30",
'$flkkjswqsg': "21",
'$flbwrjdmci': "11",
'$flkaiidxzu': "140",
'$flghbwhiij': "141",
'$flawuytxzy': "142",
'$flkuoykdct': "143",
'$flqjzijekx': "144",
'$fldbkumrch': "145",
'$flvmxyzxjh': "146",
'$flwwjkdacg': "4096",
'$flscevepor': "134",
'$flocqaiwzd': "147",
'$flpuwwmbao': "26",
'$flouvibzyw': "126",
'$flmrudhnhp': "28",
'$flhhpbrjke': "34",
'$flrkparhzh': "26",
'$flnycpueln': "125",
'$flnegilmwq': "28",
'$flyqwvfhlw': "36",
'$flqjtxmafd': "128",
'$flzlvskjaw': "25",
'$flrxmffbjl': "26",
'$flvlzpmufo': "129",
'$fldcvsitmj': "39",
'$flktwrjohv': "130",
'$flkfrjyxwm': "300",
'$flpxfiylod': "131",
'$fldusywyur': "30",
'$flbahbntyi': "300",
'$flchkrzxfi': "132",
'$flpyqymbhq': "55",
'$flnpwtojrc': "300",
'$flctswluwo': "300",
'$fljrlgnyxn': "133",
'$flgoleifxh': "134",
'$flqpcttrlm': "13",
'$fldcdylywl': "34",
'$fllvmmtgod': "26",
'$flhvcbzfrn': "37",
'$fltrngarjy': "28",
'$flkxleyzxr': "36",
'$flzufqksvp': "32771",
'$flbjfbsnip': "36",
'$flswnjceva': "36",
'$fljhoxspca': "28",
'$fldensetkm': "34",
'$flixvxwcri': "26",
'$flmjfdjlzq': "38",
'$flsmzhobco': "28",
'$flgckwhruk': "39",
'$flvqlgyufz': "36",
'$flshmkxxuh': "36",
'$flcuwkmzyt': "34",
'$flycibmgpd': "26",
'$flitcabdow': "40",
'$fliclftine': "28",
'$flinelzznd': "36",
'$fleqczuvlg': "28",
'$flokxreddk': "28",
'$flywdvownk': "36",
'$flyabzrrmv': "34",
'$flhmejjpgg': "26",
'$flvtvyiyzu': "125",
'$flvvrrdevf': "28",
'$flsvnuqocx': "36",
'$flnpzlyjmk': "34",
'$flvcsigzxl': "26",
'$flpuowucoh': "126",
'$fliccbnvun': "28",
'$floaipmnkp': "34",
'$flmlupdwyw': "26",
'$flrynetwbg': "125",
'$flpytxgnae': "28",
'$flyxgoankm': "36",
'$flgiybxvqu': "127",
'$flriujdhwu': "16",
'$flidkfvoer': "34",
'$fljhxpdlgl': "26",
'$flfqexpzzc': "35",
'$flkfnstomi': "28",
'$flioplujrx': "28",
'$flqonphkjt': "28",
'$flwcdnzybe': "36",
'$flxowoscqi': "24",
'$flofosbflo': "36",
'$flkvwonhmy': "4026531840",
'$flbkxrnxpv': "28",
'$flmgldspdj': "28",
'$fltgdgujkn': "36",
'$fltzqiggdk': "36",
'$flnyytfkei': "36",
'$flznxmaqlq': "28",
'$flrmmepznf': "34",
'$flkctwjxsv': "26",
'$flxznyhvmb': "121",
'$flzkhknuxv': "28",
'$flfhwpdvdv': "36",
'$flhaajvxmt': "36",
'$flhukovwky': "36",
'$flguylaqhb': "28",
'$fltzvugnmn': "28",
'$flfnyyixlr': "122",
'$flgsadhexo': "123",
'$flbqtuhkmy': "10",
'$flcvbsklvz': "14",
'$fljicudgov': "18",
'$fljmhypfzy': "34",
'$flcscartxg': "26",
'$flatlaxfun': "124",
'$flkyehpfcl': "28",
'$flsbvdgrpi': "34",
'$flxzavwmtk': "108",
'$flmiginejb': "109",
'$fltcctsiso': "110",
'$flvolubnxk': "111",
'$flxvccpzhb': "112",
'$flbyzxyfqo': "113",
'$flophsmbek': "114",
'$fldpastqqh': "115",
'$flvmfptzcs': "116",
'$flxireqgpl': "117",
'$flhfdxuudy': "118",
'$flfmfyahhr': "119",
'$fllsbiddpb': "34",
'$fluopltsma': "26",
'$flbnlstaug': "35",
'$flywhxdmqv': "28",
'$flgfnzsvnj': "28",
'$flbucrjuwo': "28",
'$flyafxnzcb': "36",
'$fldjwjttjz': "24",
'$flxpzbcwes': "36",
'$flkjeqhlaq': "4026531840",
'$flveiodzpl': "34",
'$flroncrwtg': "26",
'$flmymaytor': "120",
'$flwvicvsms': "83",
'$flcpbndhbq': "84",
'$fliecjfrpe': "85",
'$flghxsbhmp': "86",
'$floaidmlpx': "87",
'$fllvmncnny': "88",
'$flsfutymly': "89",
'$fluhbelzbi': "90",
'$flmnjwehod': "91",
'$flimuxorrr': "92",
'$flwlkknrpp': "93",
'$flhblipjbm': "94",
'$flubwwkeml': "95",
'$fljufrnthn': "96",
'$flktybyfdh': "97",
'$flcrizoigp': "98",
'$fldrutgtai': "99",
'$fljwnwaben': "100",
'$flxdasfsup': "101",
'$flvtsklnds': "102",
'$flgmzabuwz': "103",
'$flwrppuxsb': "104",
'$flmnmtpcbt': "105",
'$fltgxuvxht': "106",
'$fltkwhzfio': "107",
'$flyatafxxs': "58",
'$flswkvicqg': "59",
'$flevoknzhs': "60",
'$flezsvlbbu': "61",
'$flvtqedrnc': "62",
'$flusnuqyrh': "63",
'$flryydwmeb': "64",
'$flpxkdtiub': "65",
'$flmfelfgbm': "66",
'$flaqvpxefd': "67",
'$flctnooltz': "68",
'$flgdvxhtzc': "69",
'$flwehnunfj': "70",
'$fllonnyibc': "71",
'$fllzjoogng': "72",
'$floduobscm': "73",
'$flgtvyiwta': "74",
'$flevlqhfzo': "75",
'$floodysbvz': "76",
'$flzluahbyv': "77",
'$flvnfpqxze': "78",
'$flaiqgjntx': "79",
'$flcwlffkhm': "80",
'$flqcqufhqv': "81",
'$flrbuzyvzf': "82",
'$flhqanofav': "26",
'$flzjxicupp': "40",
'$flxdfspfko': "28",
'$flsermhiop': "36",
'$flcnxxwsyv': "28",
'$fldbgphumx': "28",
'$flxubnstgs': "36",
'$fletewazkh': "41",
'$flabbihpaw': "42",
'$flbymtwvbx': "43",
'$flgcijtdlm': "44",
'$fljjiooifn': "45",
'$flxfeftbwv': "46",
'$flticitoyz': "41",
'$flmstpwbrq': "47",
'$flecuynwdb': "48",
'$fljicvvbxq': "49",
'$fltonztzlf': "50",
'$flsbpkavsy': "51",
'$flxpwifgkd': "52",
'$flwxylvbjs': "53",
'$flgckmzayx': "54",
'$fltwuwurss': "55",
'$fljlijhegu': "56",
'$flwswtvquf': "57",
'$flxquvzrly': "35",
'$flshmemjjj': "28",
'$flhqjglfws': "28",
'$flwvzhffsc': "28",
'$flfrtkctqe': "36",
'$flfaxzhhen': "24",
'$fljhsdaeav': "36",
'$flvwfavfwc': "4026531840",
'$flvoretncd': "34",
'$flyxdicudb': "26",
'$flcrgsivod': "37",
'$flanaocmrr': "28",
'$flvzomlpcy': "36",
'$fleqwgegsh': "32780",
'$flnponcvdb': "36",
'$flkgskcvuw': "36",
'$flfmpbdwej': "28",
'$flfwmyxvvj': "34",
'$fljcjbfhkv': "26",
'$flggfvewxl': "38",
'$flnxzdbehd': "28",
'$fluktgcieq': "39",
'$fllueubehx': "36",
'$fllrdexkdn': "36",
'$flgrkcxavd': "34",
'$flhanaxdhn': "22",
'$flaexdqsrh': "24",
'$flgnduvhbh': "1024",
'$flsnpewutk': "25",
'$flamfdduxi': "26",
'$flcwfyxdtf': "27",
'$flafbzxahu': "28",
'$flskiskqti': "28",
'$flfbevuldl': "29",
'$flwnrvojhl': "300",
'$flllvvitvl': "375",
'$flmyerylny': "14",
'$flaevyfmea': "54",
'$floyeoxjvb': "30",
'$fluodjmwgw': "31",
'$fltibtjhtt': "32",
'$fljokrijny': "54",
'$fljevdjxae': "31",
'$flauqlvkxg': "20",
'$flxzrpavsw': "30",
'$flmdifziop': "31",
'$fldfpzzafd': "33",
'$flavwisyrl': "32",
'$fljdtvsdso': "34",
'$flexjevbco': "26",
'$flwybtlyiv': "54",
'$flhmbuoowk': "40",
'$flfbipqyue': "24",
'$flsoprhueg': "10",
'$flbzbcwqxo': "11",
'$flmmexivfs': "12",
'$flzzzdhszn': "13",
'$flfsohvcfj': "14",
'$flfstfcrlf': "15",
'$flhxyjqrtq': "16",
'$fluyicwqbf': "17",
'$flhdlfyqrt': "18",
'$flbrxfhgjg': "19",
'$flxupdtbky': "20",
'$fltnemqxvo': "97",
'$flygcayiiq': "122",
'$flbrznfbke': "15",
'$flcgkrahml': "20",
'$flbmaiufhi': "10",
'$fltmgsdyfv': "15",
'$flramjdyfu': "21",
'$flukndiwex': "22",
'$flkpnpaftg': "25",
'$flxezgjwbw': "30",
'$flsgbzulnf': "23"
}


for enc_str in mapped.keys():
  if enc_str in dec_content:
    dec_content = dec_content.replace(enc_str, mapped[enc_str])

with open('4_dec.txt', 'w') as wf:
  wf.write(dec_content)
wf.close()